spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrations: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true