apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi